version: '3'

services:
  php:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    container_name: dbhandler-devcontainer
    restart: unless-stopped
    env_file: .env
    #user: "1000:1000"
    volumes:
      - ".cfg/php/php.ini:/usr/local/etc/php/php.ini:ro"
      - "..:/dbhandler"
      - "dbhandler-vendor:/dbhandler/vendor"
    command: "tail -f /dev/null"

volumes:
  dbhandler-vendor:
